"""add_audio_path_to_word

Revision ID: 2c54bd38b211
Revises: 7aca3cd8c76a
Create Date: 2026-04-16 07:53:47.111880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c54bd38b211'
down_revision: Union[str, Sequence[str], None] = '7aca3cd8c76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('audio_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'audio_path')
    # ### end Alembic commands ###
